[sdl]
fullscreen=false
output=surface
autolock=false
overscan=10

[dosbox]
synchronize time=true
machine=vgaonly
memsize=16

[render]
frameskip=10
doublescan=false
scaler=none
autofit=true

[cpu]
core=auto
cputype=auto
cycles=auto

[voodoo]
voodoo_card=false

[mixer]
nosound=true
[midi]
mididevice=none
[sblaster]
sbtype=none
[gus]
gus=false
[innova]
innova=false

[speaker]
pcspeaker=false
tandy=off
disney=false
ps1audio=off

[autoexec]
@echo off
ver set 7.1
mount -u c
mount c ./bin/Borland_C++_3.1
mount s ./src
config -securemode
set PATH=%PATH%;C:\BORLANDC\BIN
s:
